In [1]:
import numpy as np

channels = []
for i in range(1, 6):
    fid = open(f'S-31/REGTOT11.C{i}', 'rb')
    c = np.fromfile(fid, np.int16)
    channels.append(c)

for i in channels:
    print(i)

[2118 2108 2096 ...    0    0    0]
[2628 2628 2628 ...    0    0    0]
[2051 2052 2052 ...    0    0    0]
[2076 2075 2076 ...    0    0    0]
[2892 2891 2891 ...    0    0    0]
